### ISSUE TITLE
Installing Oqtane on IIS fail

### ISSUE THREAD

**Issue by nicpitsch** [oqtane/oqtane.framework#1030]
I followed the instructions in [Oqtane Blog](https://www.oqtane.org/Resources/Blog/PostId/542/installing-oqtane-on-iis) on how to install Oqtane on IIS step by step with Oqtane 2.0.0 (except step 4 LocalDB). 

Starting the website fails with the error `An error has occurred. This application may no longer respond until reloaded. Reload.`

Browser Console content:

```
Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'.

Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.

I have added 'appSettings.Development.json' file with 'DetailedErrors: true' into installation folder. Still same error message.
```

Operating System Event Viewer content:

```
Application 'MACHINE/WEBROOT/APPHOST/OQTANE.ME' has shutdown.
```

*oqtane.me* is the *hosts* file entry: `127.0.0.1  oqtane.me`

Having some experience with IIS, Application Pools, hosts file and so on from experimenting with DNN i don't thing i made a basic error during setup. What could be wrong here? Could someone setup Oqtane 2.0.0 according to the instructions within the blog?

--
Edited: add further info:
![2021-01-02_14-02-55](https://user-images.githubusercontent.com/1652835/103457898-4e5eac00-4d03-11eb-9640-2898cfeba4fe.jpg)

**Comment by leigh-pointer** [comment]
Is this a fresh install (no database created) ?

**Comment by nicpitsch** [comment]
Yes it's a fresh install, i just downloaded the [zip](https://github.com/oqtane/oqtane.framework/releases/download/v2.0.0/Oqtane.Framework.2.0.0.Install.zip), extracted the files and so on as instructed. @leigh-pointer were you able to setup an installation according to the instructions from the blog?

**Comment by leigh-pointer** [comment]
I have just followed the blog post with no joy!

When following it seemed different to have i set it up a few months ago! 

Im going to look into this further.

**Comment by sbwalker** [comment]
@nicpitsch these instructions did work for Oqtane 1.x on .NET Core 3.1 - perhaps something changed with .NET 5. On Step 3 did you install ASP.NET Core 5.0 Runtime (v5.0.1) - Windows Hosting Bundle Installer?

**Comment by nicpitsch** [comment]
@sbwalker yes according to [Microsoft Docs - Install the ASP.NET Core Module/Hosting Bundle](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-5.0#install-the-aspnet-core-modulehosting-bundle).

**Comment by leigh-pointer** [comment]
Ok the solution is simple. Change your tld to .local and the setup page loads.  I am guessing some kind of check is going on in the browser or IIS and with .dev being available producing and issue. https://icannwiki.org/.dev 

Suggest updating the blog post 

- specify a Host name ( ie. "oqtane.dev" ) - this host name needs to be mapped to the machine and the easiest method is to follow the instructions in Step 8
"oqtane.dev" to "oqtane.local"

**Comment by sbwalker** [comment]
@leigh-pointer if you read @nicpitsch's description you will notice that he was not using "oqtane.dev" - he was using "oqtane.me". Also based on the error screen shot it appears that the request was being routed to the local IIS site - but was throwing a circuit error. So although your solution may be relevant, it does not seem to be related to the problem reported. I guess the good news is that you were able to get Oqtane 2.0 running in IIS on your local system - correct?

**Comment by nicpitsch** [comment]
Thanks @leigh-pointer. I have changed the toplevel-domain to .local on my local Windows 10 machine. Still the same error.

I tried now to install on my Windows 2016 server on a domain which has a Let's Encrypt https certificate. The 2 Error parts of the message is the same (domain name obfuscated):

```
blazor.server.js:1 [2021-01-04T14:40:37.905Z] Information: Normalizing '_blazor' to 'https://www.xxxx.yy/_blazor'.
blazor.server.js:19 [2021-01-04T14:40:37.988Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
e.log @ blazor.server.js:19
blazor.server.js:1 [2021-01-04T14:40:37.994Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.raiseOnClose (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at a (blazor.server.js:1)
```

As a conclusion i would guess my issues are not related to unsecure https connection.

**Comment by leigh-pointer** [comment]
@sbwalker yes Oqtane is running locally. 
I followed all steps although i didnt install localDB as im using SqlExpress.

**Comment by sbwalker** [comment]
@nicpitsch this definitely seems to be related to your environment. Can you enable detailed errors in the Oqtane.Server/appsettings.json:

````
{
  "DetailedErrors": true,
  "ConnectionStrings": {
    "DefaultConnection": "..."
  },
  "Runtime": "Server",
  ...
}
```

**Comment by nicpitsch** [comment]
@sbwalker i have done it. The Errors now (Windows Server, domain obfuscated):

```
blazor.server.js:1 [2021-01-04T20:03:14.094Z] Information: Normalizing '_blazor' to 'https://www.xxx.yyy/_blazor'.
blazor.server.js:19 [2021-01-04T20:03:14.203Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Startup.<>c.<ConfigureServices>b__9_3(IServiceProvider s) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Startup.cs:line 81
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.AddComponentAsync(Type componentType, ParameterView parameters, String domElementSelector)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass35_0.<<InitializeAsync>b__0>d.MoveNext()
e.log @ blazor.server.js:19
blazor.server.js:1 [2021-01-04T20:03:14.209Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.raiseOnClose (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at a (blazor.server.js:1)
```

**Comment by sbwalker** [comment]
It appears to be throwing an "Object reference not set to an instance of an object" error in Startup on this line:

                    var authToken = httpContextAccessor.HttpContext.Request.Cookies[".AspNetCore.Identity.Application"];

But is is impossible to know if the httpContextAccessor is null  or one of the dependent objects... but either way, the question is why is it throwing an error in your environment. Can you please check if there are any cookies which exist in your browser for the domain where you are trying to access the application ( https://www.xxx.yyy ). I am wondering if @leigh-pointer was encountering the same problem initially when he was using oqtane.dev as his domain - and the problem disappeared once he switched to oqtane.local ( which might be because cookies are domain specific ).

**Comment by nicpitsch** [comment]
@sbwalker as it seems i have found the cause for this issue. After adding *WebSocket* option to IIS Web Server installation the Oqtane installation finally is starting. The Microsoft docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0#signalr-configuration) and the issue [here](https://www.syncfusion.com/forums/150414/runtime-error-when-deployed-to-production) led me to it:

![2021-01-04_21-50-04](https://user-images.githubusercontent.com/1652835/103579262-40ae4f80-4ed8-11eb-96d1-a0f4609c6ed0.jpg)

So far this solves the problem on my local Windows 10 machine and also on the Windows 2016 Webserver. At the time i have not yet finished the Oqtane installation. I wanted to let you know as soon as possible the solution/cause.

**Comment by sbwalker** [comment]
I am glad you were able to resolve the problem. Note that Step 1 of the [blog](https://www.oqtane.org/Resources/Blog/PostId/542/installing-oqtane-on-iis) contains this line:

- Within Application Development Features make sure that WebSocket Protocol is enabled ( this is needed for SignalR ) 

In order to improve the blog for future users, is there a reason you decided to skip this item? Was it because it mentioned SignalR and you assumed it was optional?

**Comment by nicpitsch** [comment]
Ooh, i feel bad. The first sentence makes it clear that each step is important: *Note: even if you have IIS already installed you will want to ensure the appropriate options are enabled/disabled*. How could i overview that? 

Sorry @sbwalker and @leigh-pointer to waste your time!

**Comment by sbwalker** [comment]
@nicpitsch no worries... it was actually not a waste of time as it forced me to review some logic I had not inspected in quite some time and I now have a few action items for myself that I want to research further.
