### ISSUE TITLE
Can't deploy on azure because of swagger issues

### ISSUE THREAD

**Issue by TobiasFandrich** [oqtane/oqtane.framework#1104]
Hello,

I tried deploying the project in its basic form to Azure both from Visual Studio and by the deploy button on the repo.

By using the deploy button I always run into an error with the password policy.

By using visual studio I run into an issue with swagger. This is the error log:

`Starting to update your API
Generating swagger file to 'C:\Users\tobia\source\repos\oqtane.framework\Oqtane.Server\bin\Release\net5.0\swagger.json'.
Failed to generate swagger file. Error dotnet swagger tofile --serializeasv2 --output "C:\Users\tobia\source\repos\oqtane.framework\Oqtane.Server\bin\Release\net5.0\swagger.json" "C:\Users\tobia\source\repos\oqtane.framework\Oqtane.Server\bin\Release\net5.0\Oqtane.Server.dll" v1

Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Oqtane.Infrastructure.ILocalizationManager' while attempting to activate 'Oqtane.Startup'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName, Object instance)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_1.<BuildCommonServices>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 133
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111

Be sure that the Startup.cs for your application is calling AddSwaggerGen from within ConfigureServices in order to generate swagger file. Visit https://go.microsoft.com/fwlink/?LinkId=2131205&CLCID=0x409 for more information.`

Things I tried to fix the issue:

- set the variable "_useSwagger" to false -> no change
- reinstalled the package as per the MS Link in the error message
- tried the dev and master branch

**Comment by TobiasFandrich** [comment]
I was finally able to get it running using the Azure Deploy Button. I could help you guys out by writing a little tutorial for that as there is nothing mentioned of disabling the database security etc. which won't work on Azure.

For manual deployment using Visual Studio I had no luck. I kicked the Swagger issue with running it locally and then deploying it to Azure. But on Azure the WebApp just won't start because now it tries to access files from my local storage and I get an Alias error from MSSQL. I will tinker away with it a bit more.
