### ISSUE TITLE
Failed upgrade after publishing on IIS

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#1231]
stack trace:
Application: w3wp.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException: Access to the path 'Edit.razor' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Oqtane.Infrastructure.UpgradeManager.Upgrade_2_0_2(Tenant tenant, IServiceScope scope) in W:\projects\mfl\lib\oqtane.framework\Oqtane.Server\Infrastructure\UpgradeManager.cs:line 94
   at Oqtane.Infrastructure.UpgradeManager.Upgrade(Tenant tenant, String version) in W:\projects\mfl\lib\oqtane.framework\Oqtane.Server\Infrastructure\UpgradeManager.cs:line 40
   at Oqtane.Infrastructure.DatabaseManager.MigrateTenants(InstallConfig install) in W:\projects\mfl\lib\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 319
   at Oqtane.Infrastructure.DatabaseManager.Install(InstallConfig install) in W:\projects\mfl\lib\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 154
   at Oqtane.Infrastructure.DatabaseManager.Install() in W:\projects\mfl\lib\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 67
   at Mfl.Boot.Program.Main(String[] args) in W:\projects\mfl\src\Mfl.Boot\Program.cs:line 19

```c#
        private void Upgrade_2_0_2(Tenant tenant, IServiceScope scope)
        {
            if (tenant.Name == TenantNames.Master)
            {
                // remove Internal module template files as they are no longer supported
                var internalTemplatePath = Utilities.PathCombine(_environment.WebRootPath, "Modules", "Templates", "Internal", Path.DirectorySeparatorChar.ToString());
                if (Directory.Exists(internalTemplatePath))
                {
////// NO RIGHTS HERE -> FAIL
                    Directory.Delete(internalTemplatePath, true);

                }
            }

            // initialize SiteGuid
            var sites = scope.ServiceProvider.GetRequiredService<ISiteRepository>();
            foreach (Site site in sites.GetSites().ToList())
            {
                site.SiteGuid = System.Guid.NewGuid().ToString();
                sites.UpdateSite(site);
            }
        }
```

**Comment by sbwalker** [comment]
@chlupac  - is this a problem with Oqtane, or a configuration issue in the specific environment? I am asking because the templates exist under the wwwroot folder - which is the same folder tree where a lot of other Oqtane assets are located. So if the system throws an error performing a file/folder deletion, then there will be a lot of other functionality which will fail as well ( ie. module uninstall, theme uninstall, etc... ). Basically I am saying that even if some defensive logic is added to catch the error in the logic above, there will be a number of other areas in the framework which will fail during interaction with the application.

**Comment by erw13n** [comment]
I'm also failed when upgrade using `System Update` on Admin panel from 2.0.0 to 2.0.1, also failed update after upload Nupkg framework.
The update success when copy and paste Upgrade files.

**Comment by chlupac** [comment]
It depends on permissions in target file system. For some actions oqtane need elevated permissions, ant this should be problem in case when you do not have full access to hosting. After Publish permissions are set to default. From security point of view application itself should run at minimal level of permissions possible. Problem should be fixed with manual permissions  setup on affected folders. But in any case it should not end up with exception and irresponsible system.

**Comment by sbwalker** [comment]
The 2.0.2 release includes defensive logic to prevent the error from occurring during upgrade. The result of this is that upgrade will complete but the template files which are no longer supported will not be removed and will require manual intervention. 

In the future there will be many scenarios where assets will need to be removed on upgrade. DNN had to deal with this exact same scenario. The solution it used was during initial installation the system would actually check if it had permission to create/delete files on the file system and if not, it would not allow the user to proceed with the installation.
