### ISSUE TITLE
Error in Module Management

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1344]
**Oqtane 2.0.2**
Was moving through the pages of the Module Management then received this error.

blazor.server.js:1 [2021-05-12T19:36:07.297Z] Information: Normalizing '_blazor' to 'https://oqtane.dev/_blazor'.
blazor.server.js:1 [2021-05-12T19:36:07.725Z] Information: WebSocket connected to wss://oqtane.dev/_blazor?id=M0fE3s8pNSpIWxtkZJ9qPQ.
blazor.server.js:21 [2021-05-12T19:36:13.257Z] Error: System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at Oqtane.Modules.Admin.ModuleDefinitions.Index.UpgradeAvailable(String moduledefinitionname, String version) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Admin\ModuleDefinitions\Index.razor:line 77
   at Oqtane.Modules.Admin.ModuleDefinitions.Index.<>c__DisplayClass0_0.<BuildRenderTree>b__2(RenderTreeBuilder __builder2) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Admin\ModuleDefinitions\Index.razor:line 37
   at Oqtane.Modules.Controls.Pager`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
e.log @ blazor.server.js:21
blazor.server.js:1 [2021-05-12T19:36:13.257Z] Information: Connection disconnected.

**Comment by leigh-pointer** [comment]
Version number was not updated correctly.
