### ISSUE TITLE
Module: Cannot insert the value NULL into column 'Title', table 'Oqtane.dbo.PageModule'

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#135]
To reproduce:
1) Log in as host
2) Click Pencil to edit page
3) Click Hamburger menu to open Admin panel
4) Add counter module to page
5) get the following error:

```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Oqtane.Repository.DBContextBase.SaveChanges() in C:\Siliqon\oqtane\sbwalker.oqtane.framework\Oqtane.Server\Repository\Context\DBContextBase.cs:line 91
   at Oqtane.Repository.PageModuleRepository.AddPageModule(PageModule PageModule) in C:\Siliqon\oqtane\sbwalker.oqtane.framework\Oqtane.Server\Repository\PageModuleRepository.cs:line 41
   at Oqtane.Controllers.PageModuleController.Post(PageModule PageModule) in C:\Siliqon\oqtane\sbwalker.oqtane.framework\Oqtane.Server\Controllers\PageModuleController.cs:line 44
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

Inner Exception 1:
SqlException: Cannot insert the value NULL into column 'Title', table 'Oqtane.dbo.PageModule'; column does not allow nulls. INSERT fails.
The statement has been terminated.

```
![CounterError](https://user-images.githubusercontent.com/1857799/66972253-e3b34900-f048-11e9-92c5-4ed88820a21f.gif)

**Comment by sbwalker** [comment]
fixed in the latest PR

**Comment by ADefWebserver** [comment]
confirmed :)
