### ISSUE TITLE
Upgrading to 2.1

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#1419]
@leigh-pointer outlining some upgrade steps to follow:

- get the latest 2.1.0 source from the Dev branch (make sure you have the latest as fixes have been checked in today)
- build the code in debug mode
- ensure that there are 4 *.nupkg.bak files in your wwwroot/packages folder ( the database providers )
- replace the appsettings.json file with your 2.0.2 appsettings.json file ( the file should contain a valid connection string which points to a 2.0.2 SQL Server database )
- run the 2.1 application within Visual Studio

Expected results:

- the *.nupkg.bak files should be moved to the Oqtane.Server/Packages folder
- the Oqtane.Server/Oqtane.Database.SqlServer.1.0.0.nupkg.bak should be installed ( deleted and replaced with Oqtane.Database.SqlServer.log )
- Oqtane.Database.SqlServer.dll should have been created in the /bin
- your appsettings.json should be updated and include a Database section and AvailableDatabases section
- an __EFMigrationsHistory should have been created in your database and populated and SchemaVersions table deleted

Your application should be up and running

**Comment by leigh-pointer** [comment]
@sbwalker thanks, got that all going now.

Migrating my modules to the new framework, and not that difficult.

**Comment by sbwalker** [comment]
The one tricky item you may run into if you are converting to use EF Migrations in your module is that you will need to manually insert records into the EF Migrations History table for your past module versions. This should happen in IInstallable but there is not a code example yet ( the HtmlText module is being handled as part of the core framework upgrade - which is not the proper location ).

**Comment by cnurse** [comment]
You can check if the active database is sqlserver and then execute a Migrate.sql script like the one for Tenants (Tenant.sql)

**Comment by sbwalker** [comment]
@cnurse I merged PR #1422 today which moves the logic dealing with the HtmlText transition from SQL scripts to Mogrations from the core to the module. This includes a new method in the base class to make it easier for other module developers going through this transition.

**Comment by iJungleboy** [comment]
I tried to upgrade my installation we discussed in #1314 but it fails. No visible errors, just white screen and console shows Websockets are working. I get multiple issues.

Early on I get a AntiForgery issue - this may or may not be relevant:

```
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The key {e0e32829-6520-4e24-97de-6ebe4414aca3} was not found in the key ring.
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

After that I run into DB issues

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Oqtane.Repository.MasterDBContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DBType'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
      ClientConnectionId:d177109d-03c2-42cb-b6ee-5cd29bf4ae24
      Error Number:207,State:1,Class:16
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DBType'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
      ClientConnectionId:d177109d-03c2-42cb-b6ee-5cd29bf4ae24
      Error Number:207,State:1,Class:16
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Oqtane.Controllers.SiteController.Get (Oqtane.Server) in 22.8296ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Oqtane.Controllers.SiteController.Get (Oqtane.Server)'
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DBType'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at Oqtane.Repository.TenantRepository.<GetTenants>b__3_0(ICacheEntry entry) in C:\Projects\Oqtane\oqtane.framework\Oqtane.Server\Repository\TenantRepository.cs:line 27
         at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
         at Oqtane.Repository.TenantRepository.GetTenants() in C:\Projects\Oqtane\oqtane.framework\Oqtane.Server\Repository\TenantRepository.cs:line 24
         at Oqtane.Infrastructure.TenantManager.GetTenant() in C:\Projects\Oqtane\oqtane.framework\Oqtane.Server\Infrastructure\TenantManager.cs:line 70
         at Oqtane.Repository.DBContextBase.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Projects\Oqtane\oqtane.framework\Oqtane.Server\Repository\Context\DBContextBase.cs:line 48
         at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
         at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
         at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_EntityFinderFactory()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_Finder()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)
         at Oqtane.Repository.SiteRepository.GetSite(Int32 siteId) in C:\Projects\Oqtane\oqtane.framework\Oqtane.Server\Repository\SiteRepository.cs:line 623
         at lambda_method322(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& n
```

Suggestions?

**Comment by sbwalker** [comment]
@iJungleboy did you follow the upgrade steps at the top of this issue - or did you follow different steps? In order to reproduce we would need to know the exact steps.

**Comment by iJungleboy** [comment]
I did something slightly different which should result in the same effect

1. I ran the build installer scripts which creates IMHO all of the above in /bin/Release/net5.0/publish
2. Then copied all that unto my installation - I believe this is identical to the steps you listed

For the `appsettings.json` I tried both of these versions

1. Keep my old appsettings.json 
2. Copy a new appsettings.json and set the `DefaultDBType` as well as the `ConnectionStrings` > `DefaultConnection`

I see the packages and the `Oqtane.Database.SqlServer.dll` is in my main folder

But the page is just empty, with the log entries I posted before (once I activated logging in the `web.config`).

**Comment by iJungleboy** [comment]
Note: I did not run it in visual studio - this is an existing website configured in IIS.

**Comment by sbwalker** [comment]
@iJungleboy Uograding via deployment artifacts is totally different than upgrading via the the steps outlined above, as it is possible that artifacts may be missing from the deployment. However this is definitely a critical upgrade scenario as well. 

Can you please clarify what you mean by "I ran build installer scripts"? What exactly did you do to create the deployment artifacts?

I would suggest that you look at the release.cmd in the Oqtane.Package folder as this is what is used to create the actual release packages.

**Comment by iJungleboy** [comment]
@sbwalker I used the `release.cmd` to create my artifacts - which generates all the files in the `bin...publish` folder. That's what I meant with the "installer scripts"

**Comment by sbwalker** [comment]
Ok perfect... based on the error message it looks like the migrations are not being run. Can you share the contents of the __EFMigrationsHistory table from after the upgrade. It should provide some clues.

**Comment by sbwalker** [comment]
Can you also verify that your database did not already have an __EFMigrationsHistory table prior to performing the upgrade? And also verify that the Alias table contained values which are valid for your IIS site.

**Comment by sbwalker** [comment]
@iJungleboy are you able to post the contents of your __EFMigrationsHistory table after your attempted upgrade

**Comment by iJungleboy** [comment]
Just to ensure we don't cause new confusion: ATM I copied back all the files from before, so it's running 2.0.2 again. This "downgrade" didn't cause any trouble. This may also indicate, that no upgrade took place. But I'm just mentioning this in case running 2.0.2 on the same DB may have changed the DB again? Here's my status regarding your questions.

1. The __EFMigrationsHistory table exists now, but it's empty
2. The Aliases are configured correctly - at least as before. I have entries with www and without, and these entries don't have a protocoll (so no http or https)

**Comment by sbwalker** [comment]
@iJungleboy based on what you described, your installation is in an unsupported state as it is neither in a pure 2.0.2 state nor is it in a pure 2.1.0 state. I would suggest you restore your 2.0.2 database backup so that your database is in a 2.0.2 state - and then attempt the upgrade again with the latest code. One item I will mention is that I fixed an upgrade bug last week where the __EFMigrationsHistory was not being created properly on upgrade - which was causing errors during the upgrade as EF Core could not write to it. If you want verify that your current database has this issue - look at the data type of the AppliedDate column - if it is datetime2(7) then it is correct - if it is datetime then it is incorrect and may be causing the issues with your upgrade. Like I said above, your best approach is to try an upgrade using an actual 2.0.2 database.

**Comment by iJungleboy** [comment]
I'm not sure what `AppliedDate` you mean. If you mean on the __EFM table, there is no such field. it only has

* MigrationId
* ProductVersion

**Comment by sbwalker** [comment]
@iJungleboy I was only guessing what your problem might be... the main point is that a 2.0.2 database should not contain an __EFMigrationsHistory table

**Comment by iJungleboy** [comment]
The table might have been created on other update attempts. can I just delete it and try again @sbwalker ?

**Comment by sbwalker** [comment]
@iJungleboy the only valid test would be to use an actual 2.0.2 database - trying to use a database which is not in an officially supported state is not valid

**Comment by sbwalker** [comment]
@iJungleboy I successfully upgraded a 2.0.1 installation on IIS this morning using an Upgrade package built from the current Dev code.

**Comment by iJungleboy** [comment]
This is good to hear. I won't be able to test today but I hope Thu or Fri

**Comment by sbwalker** [comment]
@iJungleboy I tested an install of Oqtane 1.0.0 on IIS - upgrading to 2.1.0 and it worked flawlessly. I believe 2.1.0 is ready for release.

**Comment by iJungleboy** [comment]
@sbwalker that sounds awesome! great job 🚀

**Comment by iJungleboy** [comment]
@sbwalker shall I place your initial steps above into a checklist on docs.oqtane.org?

**Comment by sbwalker** [comment]
Upgrading from within Visual Studio is probably only applicable for local developer testing. The standard upgrade steps are documented here: https://www.oqtane.org/Resources/Blog/PostId/543/upgrading-oqtane

**Comment by iJungleboy** [comment]
@sbwalker ok, I think I'll duplicate that in the docs.

**Comment by sbwalker** [comment]
closing as 2.1.0 is released
