### ISSUE TITLE
Version 2.2.0. Exception when browsing to /login when you are already logged in

### ISSUE THREAD

**Issue by horacioj** [oqtane/oqtane.framework#1579]
When you browse to /login there is an exception:
Example for webassembly, but it is the same for server:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ElementReference has not been configured correctly.
System.InvalidOperationException: ElementReference has not been configured correctly.
   at Microsoft.AspNetCore.Components.ElementReferenceExtensions.GetJSRuntime(ElementReference elementReference)
   at Microsoft.AspNetCore.Components.ElementReferenceExtensions.FocusAsync(ElementReference elementReference)
   at Oqtane.Modules.Admin.Login.Index.OnAfterRenderAsync(Boolean firstRender) in ...\Oqtane.Client\Modules\Admin\Login\Index.razor:line 101
```
The problem is here:

```
   protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await username.FocusAsync();
        }
    }
```

Commenting it out solves the problem, but I'm not sure if this would be the right fix.

**Comment by sbwalker** [comment]
@leigh-pointer added the auto focus enhancement a while ago. This exception is happening because the username field does not exist in the scenario where a user is logged in. I believe the fix should be to add an additional condition check of PageState.User != null.

**Comment by leigh-pointer** [comment]
@sbwalker seen it! I am on it!
