### ISSUE TITLE
Server restart post module install fails with null exception

### ISSUE THREAD

**Issue by ghhv** [oqtane/oqtane.framework#2041]
I've been able to reproduce this issue. 

Steps:

1. Install fresh Oqtane with local MSSqlDb. 
2. Install SX2C (or Blog) module - download and click install
3. Click the toast notification to restart the server (note this also disappears on first install click)
4. Click restart from the Sys Info page. 

Which fails to restart and produces this server side:

(NOTE: manual restart works OK after this error.)

`info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [j].[JobId], [j].[CreatedBy], [j].[CreatedOn], [j].[EndDate], [j].[Frequency], [j].[Interval], [j].[IsEnabled], [j].[IsExecuting], [j].[IsStarted], [j].[JobType], [j].[ModifiedBy], [j].[ModifiedOn], [j].[Name], [j].[NextExecution], [j].[RetentionHistory], [j].[StartDate]
      FROM [Job] AS [j]
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'task1')) (Value cannot be null. (Parameter 'task1'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'task1')
   at System.Threading.Tasks.Task.WhenAny(Task task1, Task task2)
   at Oqtane.Infrastructure.HostedServiceBase.StopAsync(CancellationToken cancellationToken) in C:\Data\git\Oqtane\oqtane.framework-dev\Oqtane.Server\Infrastructure\Jobs\HostedServiceBase.cs:line 279
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.WaitForTokenShutdownAsync(IWebHost host, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Oqtane.Server.Program.Main(String[] args) in C:\Data\git\Oqtane\oqtane.framework-dev\Oqtane.Server\Program.cs:line 30
 ---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null. (Parameter 'task1')
   at System.Threading.Tasks.Task.WhenAny(Task task1, Task task2)
   at Oqtane.Infrastructure.HostedServiceBase.StopAsync(CancellationToken cancellationToken) in C:\Data\git\Oqtane\oqtane.framework-dev\Oqtane.Server\Infrastructure\Jobs\HostedServiceBase.cs:line 279
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)<---
Stopping IIS Express ...`

**And to prove the point, I just did it again after installing the BLOG module:**

`info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:44358/api/Installation/restart - 0 - 200 - - 3.9643ms
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.0 initialized 'MasterDBContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.0' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [j].[JobId], [j].[CreatedBy], [j].[CreatedOn], [j].[EndDate], [j].[Frequency], [j].[Interval], [j].[IsEnabled], [j].[IsExecuting], [j].[IsStarted], [j].[JobType], [j].[ModifiedBy], [j].[ModifiedOn], [j].[Name], [j].[NextExecution], [j].[RetentionHistory], [j].[StartDate]
      FROM [Job] AS [j]
info: Imageflow.Server.HybridCache.HybridCacheService[0]
      HybridCache is shutting down...
info: Imageflow.Server.HybridCache.HybridCacheService[0]
      HybridCache shut down in 00:00:00.0009092
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'task1')) (Value cannot be null. (Parameter 'task1'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'task1')
   at System.Threading.Tasks.Task.WhenAny(Task task1, Task task2)
   at Oqtane.Infrastructure.HostedServiceBase.StopAsync(CancellationToken cancellationToken) in C:\Data\git\Oqtane\oqtane.framework-dev\Oqtane.Server\Infrastructure\Jobs\HostedServiceBase.cs:line 279
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.WaitForTokenShutdownAsync(IWebHost host, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Oqtane.Server.Program.Main(String[] args) in C:\Data\git\Oqtane\oqtane.framework-dev\Oqtane.Server\Program.cs:line 30
 ---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null. (Parameter 'task1')
   at System.Threading.Tasks.Task.WhenAny(Task task1, Task task2)
   at Oqtane.Infrastructure.HostedServiceBase.StopAsync(CancellationToken cancellationToken) in C:\Data\git\Oqtane\oqtane.framework-dev\Oqtane.Server\Infrastructure\Jobs\HostedServiceBase.cs:line 279
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)<---
Stopping IIS Express ...`

**Comment by sbwalker** [comment]
@ghhv in order to reproduce locally it would be helpful to have some more context. Are you running on Blazor Server or Blazor WebAssembly? Is this a default installation or have you installed custom modules/themes or enabled any scheduled jobs to run after installation? By "toast notification" what are you referring to?

**Comment by ghhv** [comment]
Sorry Shaun.. more detail next time. Thanks for fixing.
