### ISSUE TITLE
Installation went fine, error after installing language pack (dutch)

### ISSUE THREAD

**Issue by trouble2** [oqtane/oqtane.framework#2268]
I installed Oqtane 3.1.3 and everything went smooth.
Then I tried to install the dutch language pack which seemed to work.
I could download, then click install, and then restart the site.
After the restart I got a 
HTTP Error 500.30 - ASP.NET Core app failed to start.

Content of the log file:

[2022-07-04 15:43:43+00:00] [Error] Connection ID "18158513706953080881", Request ID "4000003e-0002-fc00-b63f-84710c7967bb": An unhandled exception was thrown by the application.    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Oqtane.Infrastructure.InstallationManager.InstallPackages(String webRootPath, String contentRootPath) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Infrastructure\InstallationManager.cs:line 74
   at Oqtane.Infrastructure.InstallationManager.InstallPackages() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Infrastructure\InstallationManager.cs:line 33
   at Oqtane.Controllers.PackageController.InstallPackages() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Controllers\PackageController.cs:line 124
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 65
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 59
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by leigh-pointer** [comment]
Hi @trouble2 it would seem that the package is corrupt.  How this package passed the NuGet validation process, i do not know.  I will bump the minor version and rebuild and upload again.  Thanks for the feedback :)

**Comment by leigh-pointer** [comment]
@trouble2 restarting the IIS server will not work unless you remove the package from the Packages folder webroot\Packages.

I have rebuilt the package and the tested locally and it runs ok.. I uploaded to NuGet and getting the same problem.  I am going to add my local package here could you see if you have problems with this?  If its ok the then there is something go a miss with the dowload process from NuGet
[Oqtane.Client.nl-NL.3.1.3.1.nupkg.zip](https://github.com/oqtane/oqtane.framework/files/9041444/Oqtane.Client.nl-NL.3.1.3.1.nupkg.zip)


.

**Comment by trouble2** [comment]
Bedankt Leigh!

**Comment by leigh-pointer** [comment]
The zip was intentional as you are unable to attach nupkg files to a github thread.

**Comment by sbwalker** [comment]
@leigh-pointer I figured out the problem. When you created the Oqtane Registry entry for the language pack you specified the Download Url as "https://www.nuget.org/packages/Oqtane.Client.nl-NL/3.1.3.1". If you browse to that Url you will notice that it does not point to a package - it points to a web page. The proper Url should be "https://www.nuget.org/api/v2/package/Oqtane.Client.nl-NL/3.1.3.1"

**Comment by sbwalker** [comment]
I am going to improve the Oqtane Registry UI to provide guidance/validation for entering Urls.

**Comment by sbwalker** [comment]
@leigh-pointer TextBlock and RocketFuel also have this issue

**Comment by leigh-pointer** [comment]
@sbwalker oops! corrected, thanks for the heads up :)
