### ISSUE TITLE
NULL Json

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#242]
I'm not sure if this is related to #232, but in:

Admin -> Module Management -> Click on the Edit button of any module and you get.

![oc1](https://user-images.githubusercontent.com/11261164/75565052-45ce8280-5a1b-11ea-8679-5bdd9328ab16.PNG)

**Comment by chlupac** [comment]
It's probably related to #237. Did you do anything with custom modules or it's clean install?

**Comment by mikecasas** [comment]
@chlupac clean install.

**Comment by sbwalker** [comment]
Yes, there is a bug in this area:

System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Oqtane.Security.UserSecurity.GetPermissionStrings(String PermissionStrings) in C:\Siliqon\Oqtane\sbwalker.oqtane.framework\Oqtane.Shared\Security\UserSecurity.cs:line 14
   at Oqtane.Modules.Controls.PermissionGrid.OnInitializedAsync() in C:\Siliqon\Oqtane\sbwalker.oqtane.framework\Oqtane.Client\Modules\Controls\PermissionGrid.razor:line 112
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'J5jr_MKCjFDHoK1sRKF6rlr7BOHiUry0LXqdaRsbMP8'.

Will need to investigate further
