### ISSUE TITLE
Error Loading Logs Sending a lot of messages 

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2578]
Recieving an email with a error log link.
http://oqtane.local/admin/log?id=67285 

The error is not in the Event Log page, but when clicked the site generate a stream of messages.  I think we had something like this before.

**Exception**
```
Microsoft.AspNetCore.Components.NavigationException: Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.NavigateToCore(String uri, NavigationOptions options)
   at Microsoft.AspNetCore.Components.NavigationManager.NavigateToCore(String uri, Boolean forceLoad)
   at Oqtane.Modules.Admin.Logs.Index.OnParametersSetAsync() in C:\..\oqtane.framework-3.3.1\Oqtane.Client\Modules\Admin\Logs\Index.razor:line 142
```

**Properties**
`{"Error":"Exception of type \u0027Microsoft.AspNetCore.Components.NavigationException\u0027 was thrown."}`

**Comment by sbwalker** [comment]
I am able to reproduce. The problem is that the redirect is happening during pre-render which is causing an infinite loop that floods the event log. Moving the redirect to OnAfterRender seems to fix the issue... but also revealed another usability issue if the user is not logged in. I should have a fix ready shortly. Thank you for reporting this item.
