### ISSUE TITLE
Adding then Removing Permissions from the Permissions Grid

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2624]
Error
```
An Unexpected Error Has Occurred In Oqtane.Modules.HtmlText, Oqtane.Client: Collection was modified; enumeration operation may not execute.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Oqtane.Modules.Controls.PermissionGrid.ValidatePermissions() in C:\Users\Lpoint\source\repos\leigh-pointer\NewPremissions\oqtane.framework\Oqtane.Client\Modules\Controls\PermissionGrid.razor:line 322
   at Oqtane.Modules.Controls.PermissionGrid.GetPermissionList() in C:\Users\Lpoint\source\repos\leigh-pointer\NewPremissions\oqtane.framework\Oqtane.Client\Modules\Controls\PermissionGrid.razor:line 304
   at Oqtane.Modules.Admin.Modules.Settings.SaveModule() in C:\Users\Lpoint\source\repos\leigh-pointer\NewPremissions\oqtane.framework\Oqtane.Client\Modules\Admin\Modules\Settings.razor:line 210
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Steps to Reproduce

1. On an instance of the HTML module Manage Settings and select the Permissions tab
2. Check View & Edit for a Role "Registered Users"
3. Save
4. Go back and Uncheck the Permissions for the Role
5. Save
6. **An Unexpected Error Has Occurred**

**Comment by sbwalker** [comment]
@leigh-pointer please test the latest PR to determine if it resolves all of the issues

**Comment by leigh-pointer** [comment]
@sbwalker all tested and working ok.
