### ISSUE TITLE
Create module, removing module issue

### ISSUE THREAD

**Issue by tranpl** [oqtane/oqtane.framework#2692]
I created a module using the Module Creator, installed it without any modifications via the UI, restarted app. I then went into the module to edit the description, it does not save the updated changes. I then proceed to remove it, got this error:
[2023-03-20 23:35:38+00:00] [Error] An unhandled exception has occurred while executing the request.    at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 64
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 58
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2023-03-20 23:35:38+00:00] [Error] An unhandled exception has occurred while executing the request.    at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 64
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 58
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2023-03-20 23:35:39+00:00] [Error] [Oqtane.Security.AutoValidateAntiforgeryTokenFilter] AutoValidateAntiforgeryTokenFilter Failure For http://localhost:44357/api/Log 
[2023-03-20 23:35:40+00:00] [Error] An unhandled exception has occurred while executing the request.    at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 64
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 58
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2023-03-20 23:35:40+00:00] [Error] An unhandled exception has occurred while executing the request.    at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 64
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in D:\Github\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 58
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

If add the module to the home page, app adds it with the "Error loadinng {vfhy}" on the page with this error when clicking to view details:
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at VCU.vfhy.Services.vfhyService.GetvfhysAsync(Int32 ModuleId) in D:\Github\VCU.vfhy\Client\Services\vfhyService.cs:line 0
   at VCU.vfhy.Index.OnInitializedAsync() in D:\Github\VCU.vfhy\Client\Modules\VCU.vfhy\Index.razor:line 53

I then looked into the database, I see the "dbo.VCU.vfhy" table, nothing is there, hence the error message (i think). Haven't debugged it for to long. The initial module creation and installation is without issues, however if I decide to remove and install the same one..for whatever reason, it throws a fit =)

**Comment by sbwalker** [comment]
When you say "I then went into the module to edit the description" can you please explain exactly what you did? A screen shot would be helpful.

**Comment by sbwalker** [comment]
cannot reproduce based on details provided
