### ISSUE TITLE
Sub-site breaks after restart application

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#2720]
New created sub-site breaks after restart application. It is not working anymore. This issue is show-stopper for sub-site functionality in Oqtane v3.4.2.

## Steps:
1. Clean install release `Oqtane.Framework.3.4.2.Install.zip` on **IIS** (https://oqtane-poc212.oqtane.me/) with local **MS SQL** server.

![image](https://user-images.githubusercontent.com/2724850/229800872-d0ae94b0-d00d-4e2d-b071-4c73a14da7e8.png)

2. In  `Admin / Site Management` create new sub-site `s1` (https://oqtane-poc212.oqtane.me/s1)

![image](https://user-images.githubusercontent.com/2724850/229801708-5e828a97-da44-4f83-acdc-1f09daea8ce4.png)

Sub-site is created and working as expected.

![image](https://user-images.githubusercontent.com/2724850/229801816-ba8f9baa-a2b9-4754-9cfe-9f415382b2c3.png)

3. In `Admin / System Info` **Restart Application**.

![image](https://user-images.githubusercontent.com/2724850/229802386-7ceb4685-2e03-4444-8b51-0cb57f509d49.png)

**Sub-site breaks after restart.**

Administration is not working.

![image](https://user-images.githubusercontent.com/2724850/229802728-ebb153c0-3872-4fe4-9a30-b4de681d16e9.png)

Sub-site S1 home page is not working.

![image](https://user-images.githubusercontent.com/2724850/229802779-2ea77863-c011-48a1-8ba9-66e35a74a812.png)

Main site is still working.

![image](https://user-images.githubusercontent.com/2724850/229802981-77dd7199-3743-488b-9e8d-4abe10690d2d.png)

### Test again

So we can create new sub-site `s2` (https://oqtane-poc212.oqtane.me/s2)

![image](https://user-images.githubusercontent.com/2724850/229803626-380d1835-4354-4bb3-907a-8ec65405e3e3.png)

And new sub-site `s2` is working.

![image](https://user-images.githubusercontent.com/2724850/229803824-71b29c10-8acd-4b14-9bc2-bf0b81d8171a.png)

But old sub-site `s1` is not working.

![image](https://user-images.githubusercontent.com/2724850/229804077-dcf86a99-a331-4114-b748-93158dc48c87.png)

And if we **Restart Application** again, it will break sub-site 's2' also.

![image](https://user-images.githubusercontent.com/2724850/229804543-7b0e4adb-a822-4e88-85c7-fcddc51c180b.png)

![image](https://user-images.githubusercontent.com/2724850/229804663-087893d3-3ac6-4647-b2b6-c920150a95a7.png)

## aspnet core logs

[stdout_20230404124019_39184.log](https://github.com/oqtane/oqtane.framework/files/11148987/stdout_20230404124019_39184.log)

```log
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://oqtane-poc212.oqtane.me/s1/api/Site/2 - -
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Identity.Application was not authenticated. Failure message: Unprotect ticket failed
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Oqtane.Controllers.SiteController.Get (Oqtane.Server)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Site", page = ""}. Executing controller action with signature Oqtane.Models.Site Get(Int32) on controller Oqtane.Controllers.SiteController (Oqtane.Server).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Oqtane.Controllers.SiteController.Get (Oqtane.Server) in 11.903ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Oqtane.Controllers.SiteController.Get (Oqtane.Server)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Oqtane.Repository.PermissionRepository.<>c__DisplayClass5_0.<GetPermissions>b__0(ICacheEntry entry) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Repository\PermissionRepository.cs:line 39
         at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
         at Oqtane.Repository.PermissionRepository.GetPermissions(Int32 siteId, String entityName) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Repository\PermissionRepository.cs:line 31
         at Oqtane.Repository.ModuleDefinitionRepository.LoadModuleDefinitions(Int32 siteId) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Repository\ModuleDefinitionRepository.cs:line 91
         at Oqtane.Repository.ModuleDefinitionRepository.GetModuleDefinitions(Int32 siteId) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Repository\ModuleDefinitionRepository.cs:line 37
         at Oqtane.Controllers.SiteController.GetSite(Int32 siteid) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Controllers\SiteController.cs:line 103
         at Oqtane.Controllers.SiteController.<>c__DisplayClass14_0.<Get>b__0(ICacheEntry entry) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Controllers\SiteController.cs:line 68
         at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
         at Oqtane.Controllers.SiteController.Get(Int32 id) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Controllers\SiteController.cs:line 65
         at lambda_method983(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 64
         at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 58
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Request: https://oqtane-poc212.oqtane.me/s1/api/Site/2
Response status: InternalServerError Internal Server Error
```

**Comment by sbwalker** [comment]
I will investigate further.

**Comment by sbwalker** [comment]
This was related to the permission refactoring in 3.4 - the Role IDs were not being populated properly when creating a new site - which would result in a variety of unpredictable behavior
