### ISSUE TITLE
FileManager when the folder Path is set and ShowFolder = False

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#3057]
In a recent change to FileManager #3049 logic was added to show folders, however, when the Folder is set with a path like `Public` and ShowFolder = False results in an error 

<FileManager FileId="@_slideFileId" Filter="@Constants.ImageFiles" ShowFolders="false" ShowFiles="true" UploadMultiple="false" Folder=@_publicFolder @ref="fileManager" OnSelect="PopulateFileName" />

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Oqtane.Modules.Controls.FileManager.GetFiles() in C:\Projects\oqtane.framework\Oqtane.Client\Modules\Controls\FileManager.razor:line 247
   at Oqtane.Modules.Controls.FileManager.OnParametersSetAsync() in C:\Projects\oqtane.framework\Oqtane.Client\Modules\Controls\FileManager.razor:line 226
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

In this case, the FolderId should be set first based on the Path

**Comment by vnetonline** [comment]
I have also discovered that this change which was made in #3049 is preventing from uploading modules and themes the error is shown below 

```
System.FormatException: The input string 'Packages' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at Oqtane.Modules.Controls.FileManager.UploadFiles() in D:\a\1\s\Oqtane.Client\Modules\Controls\FileManager.razor:line 361
```

**Comment by sbwalker** [comment]
@vnetonline the Folder property on the FileManager was only ever intended to be used for 1 use case - uploading to the /Packages folder which is a "system" folder that does not have an entry in the Folder table in the database. If you are trying to set a specific default folder in the FileManager you should be using the FolderId property. If you look through the Oqtane framework source code you will see many examples of the usage.

**Comment by vnetonline** [comment]
@sbwalker Appreciate your answer and I understand that the folder property was mentioned for only the packages folder but by this change it would allow us to set the folder in cases like when we want to just upload images for files which are publicly able.

I could change my code in my module HeroSlider which needs to upload Hero images to publicly browsable folder

That being said I could look for a Public folder but just like Packages it would be good to set the Public folder via the folder property

**Comment by sbwalker** [comment]
@vnetonline the original post made it sound like it was an issue caused by a recent change in a prior version - however you are now clarifying that this is actually an enhancement. I will review the PR with this new context in mind.
