### ISSUE TITLE
Setting user account to "Deleted" causes InvalidOperationException if deleted user tries to login

### ISSUE THREAD

**Issue by W6HBR** [oqtane/oqtane.framework#3253]
I was testing access with an account that I changed to "Deleted" status.  Note, I did not use the deleted button in the user manager, but rather just set the deleted option on the Identity tab of User Manager.

When trying to login as the deleted user, Oqtane throws an InvalidOperationException error.  I also replicated this with a fresh install of Oqtane 4.0.2.  The error is related to antiforgery.  This also causes the browser to not allow a valid login once the error occurs.  The browser session has to be completely closed and reopened to perform a valid login with an account that is not deleted.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The provided identity of type 'System.Security.Claims.ClaimsIdentity' is marked IsAuthenticated = true but does not have a value for Name. By default, the antiforgery system requires that all authenticated identities have a unique Name. If it is not possible to provide a unique Name for this identity, consider extending IAntiforgeryAdditionalDataProvider by overriding the DefaultAntiforgeryAdditionalDataProvider or a custom type that can provide some form of unique identifier for the current user.
  Source=Microsoft.AspNetCore.Antiforgery
  StackTrace:
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenGenerator.GenerateRequestToken(HttpContext httpContext, AntiforgeryToken cookieToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetTokensInternal(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetAndStoreTokens(HttpContext httpContext)
   at Oqtane.Pages.HostModel.OnGet() in C:\Apps\Projects\Oqtane.Framework-4.0.2\Oqtane.Server\Pages\_Host.cshtml.cs:line 79
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.ActionResultHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.<InvokeHandlerMethodAsync>d__29.MoveNext()

```

**Comment by sbwalker** [comment]
thank you for reporting this issue
