### ISSUE TITLE
Bug: FileManager - "HOST" User Profile On Site(s) Other Than Master Tenant Throws a `source` Parameter Value Cannot Be Null Error Exception

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3420]
I will double check this as I am troubleshooting other issues in this area, I want to log it while it is fresh how I made this error occur.

4.0.6 Dev Branch

Exception:
```

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[Folder](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[Folder](IEnumerable`1 source, Func`2 predicate)
   at Oqtane.Modules.Controls.FileManager.GetFiles()
   at Oqtane.Modules.Controls.FileManager.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

File: UserProfile/Index.razor component module

Profile Page

Steps to reproduce:

1. install new site with latest dev branch
2. create a second site (webassembly)
3. log in as host user account used to create the site
4. visit the "Host" link in navigation for viewing the Host User Profile

**Comment by sbwalker** [comment]
I have experienced this issue as well - but only for the host account. It will need more investigation.
