### ISSUE TITLE
Internal Server Error 500 for a Request over http://

### ISSUE THREAD

**Issue by wernerzimmer** [oqtane/oqtane.framework#3474]
Our Environment installed today:

- Windows Server 2022 / SQL Server 2022
- Oqtane Framework Version 4.0.6
- Binding http and https

The request https://homepage.werner-zimmer.net/ works fine.
We check http:// and the redirect to https://. We receive a statuscode 500 Internal Server Error with InPrivate Sessions (Chrome, Edge and Opera). The Powershell command "Invoke-WebRequest -MaximumRedirection 0 -Method Get -Uri http://homepage.werner-zimmer.net/" also provide the server error.

Oqtane error.log
[2023-11-14 15:27:56+00:00] [Error] Connection ID "16429131445747843205", Request ID "40000086-0001-e400-b63f-84710c7967bb": 
An unhandled exception was thrown by the application. 
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.TryGetHttpsPort()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.LazyHelper.ThrowException()
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

Is there a configuration value to change the behavior?

**Comment by wernerzimmer** [comment]
After an update we use Oqtane Framework Version 5.0.0. The result for a http:// request is the same:

[2023-11-22 15:09:35+00:00] [Error] Connection ID "17365880163945938966", Request ID "40000017-0000-f100-b63f-84710c7967bb":
 An unhandled exception was thrown by the application. 
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.TryGetHttpsPort()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by sbwalker** [comment]
The error message contains no reference to Oqtane... it only mentions HttpsRedirectionMiddleware. I have no idea why this middleware is throwing exceptions.
