### ISSUE TITLE
Unable to upgrade to 5.0 from 4.05

### ISSUE THREAD

**Issue by tranpl** [oqtane/oqtane.framework#3488]
Not sure why its still wanting to use EF sql server 7? I tried using the compiled update zip as well as the full install zip. I also compiled it myself to make sure the package references .NET 8 versions. I
This is from the windows application log.
 
Application: w3wp.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
**Could not load file or assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=7.0.5.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.AssemblyExtensions.GetTypes(Assembly assembly, Type interfaceType) in C:\Source\Projects\oqtane.framework\Oqtane.Shared\Extensions\AssemblyExtensions.cs:line 38
   at System.Reflection.AssemblyExtensions.GetInterfaces[TInterfaceType](Assembly assembly) in C:\Source\Projects\oqtane.framework\Oqtane.Shared\Extensions\AssemblyExtensions.cs:line 23
   at Microsoft.Extensions.DependencyInjection.OqtaneServiceCollectionExtensions.AddOqtaneServices(IServiceCollection services) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Extensions\OqtaneServiceCollectionExtensions.cs:line 253
   at Microsoft.Extensions.DependencyInjection.OqtaneServiceCollectionExtensions.AddOqtane(IServiceCollection services, String[] installedCultures) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Extensions\OqtaneServiceCollectionExtensions.cs:line 38
   at Oqtane.Startup.ConfigureServices(IServiceCollection services) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Startup.cs:line 97
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Oqtane.Server.Program.BuildWebHost(String[] args) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Program.cs:line 34
   at Oqtane.Server.Program.Main(String[] args) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Program.cs:line 19
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.SqlServer, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by tranpl** [comment]
I went to add the package to the csproj for the server app and used the output to uploaded it manually to the application. 
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
