### ISSUE TITLE
Installing Oqtane Theme Crashes Beta

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#356]
- Went to themes
- downloaded Oqtane 0.5 theme
- clicked install

browser dissappeared or crashed... unable to launch site after from VS.

Maybe something I am doing wrong I am trying to test out themes.  One thing v1 users will want to do is create new themes so I was going to see what I could create from ideas in the Oqtane theme however ran into this issue. 

> System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Could not load file or assembly 'Oqtane.Client, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'Oqtane.Client, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'Oqtane.Client, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.Reflection.AssemblyExtensions.GetTypes(Assembly assembly, Type interfaceType) in C:\OQTANE\oqtane.framework-0.0.9-beta1\oqtane.framework-0.0.9-beta1\Oqtane.Server\Extensions\AssemblyExtensions.cs:line 31
   at System.Reflection.AssemblyExtensions.GetInterfaces[TInterfaceType](Assembly assembly) in C:\OQTANE\oqtane.framework-0.0.9-beta1\oqtane.framework-0.0.9-beta1\Oqtane.Server\Extensions\AssemblyExtensions.cs:line 16
   at Microsoft.Extensions.DependencyInjection.OqtaneServiceCollectionExtensions.AddOqtaneServices(IServiceCollection services) in C:\OQTANE\oqtane.framework-0.0.9-beta1\oqtane.framework-0.0.9-beta1\Oqtane.Server\Extensions\OqtaneServiceCollectionExtensions.cs:line 57
   at Oqtane.Startup.ConfigureServices(IServiceCollection services) in C:\OQTANE\oqtane.framework-0.0.9-beta1\oqtane.framework-0.0.9-beta1\Oqtane.Server\Startup.cs:line 192
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Oqtane.Program.Main(String[] args) in C:\OQTANE\oqtane.framework-0.0.9-beta1\oqtane.framework-0.0.9-beta1\Oqtane.Server\Program.cs:line 13

![image](https://user-images.githubusercontent.com/13577556/78959822-f3b06080-7aa0-11ea-8440-bfe2b31642dc.png)

also:  

  | Name | Value | Type
-- | -- | -- | --
  | Message | "Unable to load one or more of the requested types.\r\nCould not load file or assembly 'Oqtane.Client, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.\r\nCould not load file or assembly 'Oqtane.Client, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.\r\nCould not load file or assembly 'Oqtane.Client, Version=0.0.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified." | string

**Comment by thabaum** [comment]
Removed the Oqtane.Theme.Custom.dll file from the oqtane.server/bin/debug folder as discussed in Gitter chat and the domain fired off again.

- Admin Dashboard
- Theme Management
- Install Theme
- **Download Theme** Oqtane Custom Theme
- Click Install

The server page shutsdown or closes and debug info files.  I will do it again so I can see what may be important that is missing here.

I know it reports "File not found" so it seems like it is looking to load something but fails to once the dll gets installed.

**Comment by chlupac** [comment]
I'm unable to reproduce this error.

**Comment by sbwalker** [comment]
@thabaum if you are using the beta 0.9 package from this location: https://github.com/oqtane/oqtane.framework/releases it will definitely throw an error as the new version of the custom theme package uses the new implementation for the ITheme interface. You should pull the latest Oqtane code and build the solution.

**Comment by sbwalker** [comment]
I think the action item here ( if @thabaum can confirm ) is that I need to publish a 0.9.1 beta package which contains the latest changes

**Comment by thabaum** [comment]
I think a beta package every 1-3 weeks on average few times before a release would be nice when some important changes are made or a series of "breaking" changes... "checkpoints" that make it worth testing the repo as a new beta and RC versions.

**Comment by sbwalker** [comment]
I just published a 0.9.0 release package yesterday. From this point on all packages will be upgradeable.

**Comment by sbwalker** [comment]
I will publish a new theme package today which is compatible.
