### ISSUE TITLE
BUG: Oqtane.MAUI application will not run currently (Hybrid 5.0.3)

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3753]
### Issue

Oqtane.Maui App is not working in the current dev branch 5.0.3 once PR 3714

### Current Behavior

Prior to this commit .NET Maui App worked and all commits after seem to produce a few different behaviors as described below:

- PR #3714 - Hybrid Not Enabled Error - https://github.com/oqtane/oqtane.framework/commit/cef56cb5f193efb8a7360cacf26bf9e847276e8c

- PR #3722 - Hybrid Not Enabled Error still exists eb25d9d7af247d692e305f74aab7b188f929c244

- PR #3727 to #3729 - .NET Maui project build error in MauiProgram.cs builder.Services.AddOqtaneAuthorization();

- PR #3730 to Current commit - Error in .NET Maui F12 dev tools displays:
```
DynamicComponent requires a non-null value for the parameter Type.
   at Microsoft.AspNetCore.Components.DynamicComponent.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
NotifyUnhandledException @ blazor.webview.js:1
```

### Additional Context
After reviewing the Main.razor code and this error it looks like maybe the Oqtane.UI.Routes Type maybe not set properly, I never seen the Maui app work after PR #3714 so it is hard to say. Since that error is not displayed relating to Hybrid not enabled in later commits it may not relate.

**Comment by thabaum** [comment]
Since updating the packages I have moved on to a new error in ModuleMessage.razor:

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/f2c7a3b5-bfb6-463a-85d4-0c7153a80dc8)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Oqtane.Client
  StackTrace:
   at Oqtane.Modules.Controls.ModuleMessage.BuildRenderTree(RenderTreeBuilder __builder) in C:\Dev\Oqtane\commits\oqtane.framework\Oqtane.Client\Modules\Controls\ModuleMessage.razor:line 12

```

I may need to refresh my branch again to be sure no other changes are causing this, but I am fairly positive I only updated the package dependencies.

**Comment by thabaum** [comment]
closed in #3792

**Comment by thabaum** [comment]
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/3e68c265-4ee5-4bda-a871-504aeb7212f6)
```
Cannot supply a component of type 'Oqtane.UI.RenderModeBoundary' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
NotifyUnhandledException @ blazor.webview.js:1
```
New issue so I will re-open this. 

Maybe a static SSR issue so should be logged separately and rename this one to .NET Maui Lost Connectivity issue?

I will re-open for now and see if I can resolve.

**Comment by thabaum** [comment]
I am going to close this issue as fixed in https://github.com/oqtane/oqtane.framework/pull/3792

The new issue is mentioned above, and I will generate a new issue relating as it seems to be limited to when switching to static SSR and rendering of the UI controls in the menu.
