### ISSUE TITLE
Bug: Oqtane.Maui - App Interactive Render Modes Not Supported In Program Component Errors (5.0.3 Hybrid Static SSR )

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3793]
### Description

App Interactive Render Modes Not Supported In Program Component Errors (5.0.3 Static SSR)

### How to Reproduce
(Apply recent fix #3792 first)
1. Launch .NET Maui Oqtane app after launching the server app in Global Interactivity Hosting Mode with Hybrid enabled.
2. Notice all works as expected except the navigation control buttons are not styled.  (another issue)
3. Switch Site Settings to: Hybrid Enabled - Static Server Rendering.
4. Click on a Button Located In The Navigation User/Admin UI Controls.
5. Notice Error As Shown Here:
```
blazor.webview.js:1  Cannot supply a component of type 'Oqtane.Themes.Controls.ControlPanelInteractive' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
6. Close the Maui App, Rebuild, Build, Deploy and Relaunch it the app will run.
7. Click on a button control in navigation if you did not before and Notice the New Error Shown Below:

App Interactive Render Modes Not Supported In Program Component Errors (5.0.3 Static SSR)
```
blazor.webview.js:1  Cannot supply a component of type 'Oqtane.UI.RenderModeBoundary' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   ```

### Screenshots
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/8d6e75df-1ff5-4c5a-ae43-9cd4b8076fc3)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/e383b90e-1050-40b6-8a0f-bb941028abe2)

### Addtional Context

To see this work again with interactivitity while switching between interactivity hosting models - clear all cache be sure to build the server project first then the maui project to get the latest dlls to clear the old VS data or something... pain in the... but it is the only way I have been able to fresh things up for testing between render mode switching.

Maybe in production this will not be an issue but this is a behavior to observe more.

**Comment by thabaum** [comment]
I am closing this issue as I found the problem,

If you change render modes in the UI, you must rebuild, build the Oqtane.Server app... then Clean, Rebuild, Build, Deploy the Oqtane.Maui project and you will see these errors vanish.  I overkilled all those buttons, but it seems to be the only fool proof way to be sure I have a clean start.   Along with Control + F5 in the Maui App if additional help is needed.

I am not sure why, but this was causing false flags.

**Comment by thabaum** [comment]
Reopening, I sometimes think I am on MAUI app, I was on the browser.  Still an issue.

**Comment by sbwalker** [comment]
.NET MAUI does not support render modes - it uses a completely different approach to component rendering based on WebView. The .NET MAUI client passes parameter values for RenderMode and RunTime to the Routes component. These values are preserved in PageState so they are available throughout the framework. And scenario where the rendermode boundary is dynamic  and needs to support static or interactive, there is conditional logic for declaring the components. This conditional logic needs to utilize PageState.RenderMode rather than PageState.Site.RenderMode - as the latter is the preference for the site specified by the administrator - it is not the actual render mode passed to the Routes component. #3797 resolves this issue and allows .NET MAUI to work properly regardless of the site preference specified.

**Comment by sbwalker** [comment]
Note that in order to support .NET MAUI you cannot declare the ```@rendermode``` attribute within a component itself - as this will throw a run-time exception if the component is used in .NET MAUI (because it does not support render modes). This is fine from an Oqtane perspective, as declaring the ```@rendermode``` attribute within a component itself also does not support state management (ie. PageState or ModuleState) . So this approach should never be used.

**Comment by thabaum** [comment]
@iJungleboy  This is documentation worthy:

> Note that in order to support .NET MAUI you cannot declare the @rendermode attribute within a component itself - as this will throw a run-time exception if the component is used in .NET MAUI (because it does not support render modes). This is fine from an Oqtane perspective, as declaring the @rendermode attribute within a component itself also does not support state management (ie. PageState or ModuleState) . So this approach should never be used.

**Comment by thabaum** [comment]
@sbwalker so how does the .NET Maui app run?  Does it run purely whatever is set as global interactive or global static only with no support for switching between the render modes per page/component?

**Comment by sbwalker** [comment]
@thabaum the rendermode settings are irrelevant for .NET MAUI - components are rendered natively in a WebView, and they are always "interactive" (although in this context "interactive" does not have anything to do with WebAssembly or SignalR as it does not use either of those technologies - .NET MAUI is a native client application - not a browser).

**Comment by thabaum** [comment]
@sbwalker thanks for the clarification.  I was doing a lot of reading on WebView and BlazorWebView documentation reviewing how they are used in Oqtane and the difference between them.  That will help me stay on the right track.  Thank you.
