### ISSUE TITLE
Bug: Home page display error when first loading

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#3951]
**Reproduce Steps**
1. build the code in visual studio and run it.

**Expected Result**
Home page loaded without any error.

**Actually Result**
Home page display error when first loading, and it will display correctly after reload the page.
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/bb163408-f9e4-4036-95f6-5e5cf7d244a6)

**Exception from error logs**
System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__195_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Oqtane.Modules.HtmlText.Repository.HtmlTextRepository.<>c__DisplayClass8_0.<<GetHtmlTextsAsync>b__0>d.MoveNext() in E:\Git\zyhfish\oqtane.framework\Oqtane.Server\Modules\HtmlText\Repository\HtmlTextRepository.cs:line 61
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Oqtane.Modules.HtmlText.Repository.HtmlTextRepository.GetHtmlTextsAsync(Int32 moduleId) in E:\Git\zyhfish\oqtane.framework\Oqtane.Server\Modules\HtmlText\Repository\HtmlTextRepository.cs:line 58
   at Oqtane.Modules.HtmlText.Services.ServerHtmlTextService.GetHtmlTextAsync(Int32 moduleId) in E:\Git\zyhfish\oqtane.framework\Oqtane.Server\Modules\HtmlText\Services\HtmlTextService.cs:line 50
   at Oqtane.Modules.HtmlText.Index.OnParametersSetAsync() in E:\Git\zyhfish\oqtane.framework\Oqtane.Client\Modules\HtmlText\Index.razor:line 28

**Comment by zyhfish** [comment]
Hi @sbwalker , should this be transient but not scoped so that the service will be new instance every time request to it:
https://github.com/oqtane/oqtane.framework/blob/be155f8c6cb117e0e4a375c1eb186e9fcaf689df/Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs#L313

**Comment by sbwalker** [comment]
@zyhfish you are correct - fixed by #3953

**Comment by sbwalker** [comment]
@zyhfish an error is still happening even after the change to use Transient scope. If you navigate between the Home / Private / MyPage pages after running the framework, this method:

```
        public async Task<IEnumerable<Models.HtmlText>> GetHtmlTextsAsync(int moduleId)
        {
            return await _cache.GetOrCreateAsync($"HtmlText:{_siteState.Alias.SiteKey}:{moduleId}", async entry =>
            {
                entry.SlidingExpiration = TimeSpan.FromMinutes(30);
                return await _db.HtmlText.Where(item => item.ModuleId == moduleId).ToListAsync();
            });
        }
```
is throwing an error:

Error Loading Content There is already an open DataReader associated with this Connection which must be closed first.

Note that the DBContext for the Html/Text module is Transient scoped as well. 

I do see these warnings for EF Core when it comes to using async:

"EF Core doesn't support multiple parallel operations being run on the same context instance. You should always wait for an operation to complete before beginning the next operation. This is typically done by using the await keyword on each async operation.

The async implementation of [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient) unfortunately has some known issues (e.g. [#593](https://github.com/dotnet/SqlClient/issues/593), [#601](https://github.com/dotnet/SqlClient/issues/601), and others). If you're seeing unexpected performance problems, try using sync command execution instead, especially when dealing with large text or binary values."

If EF Core cannot be reliably used in async scenarios then we may need to revert back to using the HttpClient approach.

**Comment by sbwalker** [comment]
This article provides guidance on EF Core DBContext, Blazor, and multi-tenancy:

https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy

Oqtane most likely needs a DBContextFactory which replicates the functionality of the existing DBContextBase but avoids DI and supports the process model of server-side Blazor.

**Comment by sbwalker** [comment]
One more observation... this issue is actually occurring in a statically rendered component - so there is no SignalR circuit (Blazor Server) in this scenario.

**Comment by sbwalker** [comment]
#3959 resolves the issue for the Html/Text module but is not a complete solution as OqtaneServiceCollectionExtensions.cs needs a way to call AddDbContextFactory dynamically

**Comment by sbwalker** [comment]
Recording some additional information for future context...

Let's say you have Page1 and Page2 in Oqtane and they each have their own Html/Text module assigned (ie. each module instance has a different ModuleId in Oqtane). The default component for the Html/Text module is the Index.razor component. So when Page1 is rendered, an Index component is created - which creates services and loads the content based on the ModuleId. When you navigate to Page2 you would assume that the previous component instance and its services are disposed and a new component instance and services are created. However this is NOT the case. Blazor notices that the component type is the same and is in the same location in the DOM so it re-uses the same component instance. So this means that a component can actually stay alive for MULTIPLE server requests. So this is why a DbContext which is Transient scoped can sometimes be re-used by a component and exhibit strange behavior and errors. This is why Microsoft recommends using a DbContextFactory for server-side Blazor.

**Comment by sbwalker** [comment]
I just realized that the IServerStartup interface can be used for registering the DbContextFactory. A module simply needs to provide a class implementing IServerStartup:

```
    public class HtmlTextDbContextFactory : IServerStartup
    {
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            // not implemented
        }

        public void ConfigureMvc(IMvcBuilder mvcBuilder)
        {
            // not implemented
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContextFactory<HtmlTextContext>(opt => { }, ServiceLifetime.Transient);
        }
    }
```
