### ISSUE TITLE
[ISSUE] - The renderer does not have a component with ID 82.

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4116]
### Oqtane Info

Version - 5.1.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the ISSUE

I have a module when I add a new item to the module I am getting the the following error 

The module has several action such as Manage, Add Course etc 

When I go to manage screen and then go to Add Course Action I get the error which occurs in RenderModeBoundry

The renderer does not have a component with ID 82.

System.ArgumentException: The renderer does not have a component with ID 83.
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.SendBatchAsStreamingUpdate(RenderBatch& renderBatch, TextWriter writer)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

I am using Radzen Components, when I turn off the Prerender at server the above error doesn't come up!

**Comment by zyhfish** [comment]
Hi @vnetonline , could you please provide the module install package so that I can have a chance to reproduce the issue.

**Comment by vnetonline** [comment]
> Hi @vnetonline , could you please provide the module install package so that I can have a chance to reproduce the issue.

Where do you want me to send it ?

**Comment by vnetonline** [comment]
It seems this has been resolved by #4118 by removing StreamRendering attribute

**Comment by sbwalker** [comment]
ok, this is good news... I will close this issue

**Comment by vnetonline** [comment]
I have just noticed this error is back in 5.1.1

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/07c3b7f2-1db9-4048-93ed-8199cc6ebe22)
