### ISSUE TITLE
[BUG] Error ExceptionMiddleware

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4498]
### Oqtane Info

Version - 5.2.0
Render Mode - interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
Receive a lot of error log emails but seems intermittent. 

The log:
![image](https://github.com/user-attachments/assets/f4445ab9-2c4a-4668-8f83-4a6f512581a8)

The exception
```
System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.CopyImpl(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Oqtane.Repository.ModuleDefinitionRepository.ProcessModuleDefinitions(Int32 siteId) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\ModuleDefinitionRepository.cs:line 224
   at Oqtane.Repository.ModuleDefinitionRepository.<>c__DisplayClass14_0.<LoadModuleDefinitions>b__0(ICacheEntry entry) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\ModuleDefinitionRepository.cs:line 118
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Oqtane.Repository.ModuleDefinitionRepository.LoadModuleDefinitions(Int32 siteId) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\ModuleDefinitionRepository.cs:line 115
   at Oqtane.Repository.ModuleDefinitionRepository.GetModuleDefinitions(Int32 siteId) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\ModuleDefinitionRepository.cs:line 43
   at Oqtane.Repository.SiteRepository.InitializeSite(Alias alias) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Repository\SiteRepository.cs:line 174
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 56
   at Oqtane.Infrastructure.ExceptionMiddleware.Invoke(HttpContext context, IServiceProvider provider) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Infrastructure\Middleware\ExceptionMiddleware.cs:line 25

```

**Comment by sbwalker** [comment]
I am not sure how to reproduce this issue. The Oqtane line of code with the exception is line 224 in ModuleDefinitionRepository.cs:

serverState.Assemblies.Insert(0, assembly.Trim());

which is basically adding any Dependencies which have been defined in the IModule interface to a List which can be used when running on WebAssembly so that it knows which DLLs need to be downloaded to the client browser. I am not sure how adding an item to a standard List can result in "Destination array was not long enough"?

Do you have custom modules where you are defining Dependencies? Is this only happening in development, or also in production? Are you able to put a breakpoint on this line of code to determine which assembly is triggering the error?

**Comment by zyhfish** [comment]
this maybe a race condition issue that the ProcessModuleDefinitions called in the same time, but the code is not thread safe.

**Comment by sbwalker** [comment]
@zyhfish the TenantMiddleware has the following logic to handle the first request to a site:

```
                    // handle first request to site
                    var serverState = context.RequestServices.GetService(typeof(IServerStateManager)) as IServerStateManager;
                    if (!serverState.GetServerState(alias.SiteKey).IsInitialized)
                    {
                        var sites = context.RequestServices.GetService(typeof(ISiteRepository)) as ISiteRepository;
                        sites.InitializeSite(alias);
                    }
```

and InitializeSite uses a lock to ensure the logic is only executed once:

```
        public void InitializeSite(Alias alias)
        {
            var serverstate = _serverState.GetServerState(alias.SiteKey);
            if (!serverstate.IsInitialized)
            {
                // ensure site initialization is only executed once
                lock (_lock)
                {
                    if (!serverstate.IsInitialized)
                    {
                        var site = GetSite(alias.SiteId);
                        if (site != null)
                        {
                            // initialize theme Assemblies
                            site.Themes = _themeRepository.GetThemes().ToList();

                            // initialize module Assemblies
                            var moduleDefinitions = _moduleDefinitionRepository.GetModuleDefinitions(alias.SiteId);
```

this is where the module assemblies list is initialized.
