### ISSUE TITLE
[BUG] Antiforgery Token Error in System Info > Log after Restarting Application or Upgrading Site

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4656]
### Oqtane Info

Version - 5.2.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

```

[2024-09-23 19:09:32+00:00] [Error] An exception was thrown while deserializing the token.    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
### Expected Behavior

```

### Steps To Reproduce

Restart the application
Review log in System Info > Log

### Anything else?

Maybe this can be safely ignored as the host user gets logged out?

This happens 3 times on upgrade, one time on a general restart of the application.
![image](https://github.com/user-attachments/assets/2fc55a34-4bf6-4944-be22-1ec06c5f8746)

**Comment by sbwalker** [comment]
this can be safely ignored without any side effects
