### ISSUE TITLE
[BUG] Cannot Add New Site To Existing Installation Using Separate Database On IIS

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#4675]
### Oqtane Info

Version - 5.2.3
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

Reported by @JanOlsmar in #4665. Adding a new site to an existing installation using a separate database on IIS produces an exception:

```
An Error Occurred Migrating The Database For Tenant test. This Is Usually Related To Database Permissions, Connection String Mappings, Or The Database Not Being In A Supported State. System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Oqtane.Infrastructure.DatabaseManager.MigrateTenants(InstallConfig install) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 377 
```

### Expected Behavior

Site is created without exception

### Steps To Reproduce

Install Oqtane 5.2.3 on IIS
Login as host and navigate to Site Management
Select Add Site
Specify Site Name of "test" and Alias of "localhost:44357/test" and specify Create New Database
Enter Host Username and Password
Click Create

**Comment by sbwalker** [comment]
fixed in #4676
