### ISSUE TITLE
[BUG]  Install Oqtane using Postgres DB

### ISSUE THREAD

**Issue by HQuast** [oqtane/oqtane.framework#4796]
### Oqtane Info

Version - 5.2.4
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Install Oqtane on a Windows system using Oqtane.Framework.5.2.4.Install.zip.  Choose Postgres as a DB storage. 

### Steps To Reproduce
Unzip Oqtane.Framework.5.2.4.Install.zip.  
On a cmd prompt run  "dotnet  .\Oqtane.Server.dll --urls=http://+:8080  " in the  unzipped folder.
Stacktrace: 
Oqtane.Infrastructure.DatabaseManager[0]
      [Oqtane.Infrastructure.DatabaseManager] An Error Occurred Provisioning The Master Database. This Is Usually Related To The Master Database Not Being In A Supported State. System.NullReferenceException: Object reference not set to an instance of an object.
         at EFCore.NamingConventions.Internal.SnakeCaseNameRewriter.RewriteName(String name)
         at Oqtane.Database.PostgreSQL.PostgreSQLDatabase.RewriteName(String name) in C:\Source\Projects\oqtane.framework\Oqtane.Database.PostgreSQL\PostgreSQLDatabase.cs:line 87
         at Oqtane.Migrations.EntityBuilders.BaseEntityBuilder`1.RewriteName(String name) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Migrations\EntityBuilders\BaseEntityBuilder.cs:line 50
         at Oqtane.Migrations.EntityBuilders.BaseEntityBuilder`1.AddForeignKey(CreateTableBuilder`1 table, ForeignKey`1 foreignKey) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Migrations\EntityBuilders\BaseEntityBuilder.cs:line 379
         at Oqtane.Migrations.EntityBuilders.BaseEntityBuilder`1.AddKeys(CreateTableBuilder`1 table) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Migrations\EntityBuilders\BaseEntityBuilder.cs:line 368
         at Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateTable[TColumns](String name, Func`2 columns, String schema, Action`1 constraints, String comment)
         at Oqtane.Migrations.EntityBuilders.BaseEntityBuilder`1.Create() in C:\Source\Projects\oqtane.framework\Oqtane.Server\Migrations\EntityBuilders\BaseEntityBuilder.cs:line 421
         at Oqtane.Migrations.Master.InitializeMaster.Up(MigrationBuilder migrationBuilder) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Migrations\Master\01000000_InitializeMaster.cs:line 25
         at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
         at Microsoft.EntityFrameworkCore.Migrations.Migration.get_UpOperations()
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.Migrate(String targetMigration)
         at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
         at Oqtane.Infrastructure.DatabaseManager.MigrateMaster(InstallConfig install) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Infrastructure\DatabaseManager.cs:line 271

### Anything else?

I think the reason is  the ForeignKey struct .  There are two constructors.  The only one used in the code is the one that lead to set "PrincipalSchema" to null.  That causes the crash of the Postgres migragtion.  Setting  "PrincipalSchema" to string.Emty seems to work.

**Comment by sbwalker** [comment]
This was already reported and fixed here: https://github.com/oqtane/oqtane.framework/pull/4786
